services:

  parkour2-caddy:
    image: caddy:2
    container_name: parkour2-caddy
    restart: unless-stopped
    ports:
      - "9980:9980"
      - "9981:9981"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ../media:/parkour2/media
      - parkour2_staticfiles:/parkour2/static
      # ./cert.pem:/etc/ssl/cert.pem:ro
      # ./key.pem:/etc/ssl/key.pem:ro


volumes:
  caddy_data:
  caddy_config:
  parkour2_staticfiles:
    external: true


networks:
  parkour2_default:
    external: true