# Generated by Django 3.2.14 on 2022-08-12 14:30

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oidc_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='OIDC ID'),
        ),
        migrations.AlterField(
            model_name='costunit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='costunit',
            name='pi',
            field=models.ForeignKey(on_delete=models.SET(common.models.get_deleted_pi), to='common.principalinvestigator', verbose_name='Principal Investigator'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='principalinvestigator',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='principalinvestigator',
            name='organization',
            field=models.ForeignKey(on_delete=models.SET(common.models.get_deleted_org), to='common.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
