# Generated by Django 3.2.14 on 2022-08-14 15:19

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20220812_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('pi', models.ForeignKey(on_delete=models.SET(common.models.get_deleted_pi), to='common.principalinvestigator', verbose_name='Principal Investigator')),
            ],
            options={
                'verbose_name': 'OpenID Group',
                'verbose_name_plural': 'OpenID Groups',
                'ordering': ['name'],
            },
        ),
    ]
