# Generated by Django 3.2.20 on 2023-08-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_dj32_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pi',
            field=models.BooleanField(default=False, verbose_name='PI Account'),
        ),
    ]
