# Generated by Django 3.2.14 on 2022-08-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_oidc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bioinformatician',
            field=models.BooleanField(default=False, verbose_name='Is bioinformatician?'),
        ),
    ]
