# Generated by Django 3.2.20 on 2023-08-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_user_is_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='principalinvestigator',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
