# Generated by Django 3.2.15 on 2022-08-23 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_oidcgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='principalinvestigator',
            name='parent_user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
