# Generated by Django 3.2.20 on 2023-09-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_duty_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='costunit',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
