# Generated by Django 3.2.20 on 2023-10-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_costunit_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
