# Generated by Django 4.2.6 on 2023-10-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0009_remove_duty_facility"),
    ]

    operations = [
        migrations.AddField(
            model_name="principalinvestigator",
            name="email",
            field=models.EmailField(
                default="Unset", max_length=254, verbose_name="E-Mail Address"
            ),
        ),
    ]
