# Generated by Django 3.2.15 on 2022-09-21 14:58

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_user_is_bioinformatician'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cost_unit',
            field=models.ManyToManyField(blank=True, to='common.CostUnit', verbose_name='Cost Unit'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pi',
            field=models.BooleanField(default=False, help_text='Designates whether a user is a Principal Investigator.', verbose_name='Principal Investigator status'),
        ),
        migrations.AlterField(
            model_name='costunit',
            name='pi',
            field=models.ForeignKey(on_delete=models.SET(common.models.get_deleted_pi), to=settings.AUTH_USER_MODEL, verbose_name='Principal Investigator'),
        ),
        migrations.AlterField(
            model_name='oidcgroup',
            name='pi',
            field=models.ForeignKey(on_delete=models.SET(common.models.get_deleted_pi), to=settings.AUTH_USER_MODEL, verbose_name='Principal Investigator'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pi',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Principal Investigator'),
        ),
        migrations.DeleteModel(
            name='PrincipalInvestigator',
        ),
    ]
