# Generated by Django 3.2.16 on 2023-03-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowcell', '0004_auto_20230308_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencer',
            name='lanes',
        ),
    ]
