# Generated by Django 3.2.20 on 2023-08-21 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import index_generator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.PositiveSmallIntegerField(default=1, verbose_name='Multiplier')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Size')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
            ],
            options={
                'ordering': ['multiplier', 'size'],
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('loaded', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Loaded')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('libraries', models.ManyToManyField(blank=True, related_name='pool', to='library.Library')),
                ('samples', models.ManyToManyField(blank=True, related_name='pool', to='sample.Sample')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index_generator.poolsize', verbose_name='Size')),
                ('user', models.ForeignKey(on_delete=models.SET(index_generator.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
