# Generated by Django 3.2.15 on 2022-10-27 12:35

import django.db.models.deletion
import index_generator.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("index_generator", "0003_poolsize_obsolete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pool",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pool",
            name="size",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="index_generator.poolsize",
                verbose_name="Size",
            ),
        ),
        migrations.AlterField(
            model_name="pool",
            name="user",
            field=models.ForeignKey(
                on_delete=models.SET(index_generator.models.get_sentinel_user),
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="poolsize",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
