services:
  parkour2-vite:
    container_name: parkour2-vite
    hostname: parkour2-vite
    build:
      dockerfile: ./frontend.Dockerfile
    restart: always
    volumes:
      - ./frontend:/usr/src/app

  parkour2-postgres:
    container_name: parkour2-postgres
    image: postgres:latest
    env_file:
      - ./misc/parkour.env
    restart: always
    volumes:
      - pgdb:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
    ports:
      - 5432:5432

  parkour2-django:
    container_name: parkour2-django
    hostname: parkour2-django
    build:
      dockerfile: ./backend.Dockerfile
      target: pk2_base
    env_file:
      - ./misc/parkour.env
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - media:/usr/src/app/media
      - staticfiles:/usr/src/app/staticfiles
    depends_on:
      parkour2-postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgdb:
  media:
  staticfiles:


networks:
  parkour2_default:
    external: true
