# Generated by Django 4.2.9 on 2024-02-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_sample_shared", "0009_archived_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryprotocol",
            name="type",
            field=models.CharField(
                choices=[("DNA", "DNA"), ("RNA", "RNA"), ("Cells", "Cells")],
                default="DNA",
                max_length=5,
                verbose_name="Type",
            ),
        ),
    ]
