# Generated by Django 3.2.16 on 2023-10-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_alter_nucleicacidtype_type'),
        ('library_sample_shared', '0012_auto_20230929_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryprotocol',
            name='nucleic_acid_type',
        ),
        migrations.AddField(
            model_name='libraryprotocol',
            name='nucleic_acid_types',
            field=models.ManyToManyField(to='sample.NucleicAcidType', verbose_name='nucleic acid type'),
        ),
    ]
