# Generated by Django 4.2.19 on 2025-04-29 08:23

import django.core.validators
from django.conf import settings
import re
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import logging
import re

logger = logging.getLogger(__name__)


def clean_library_protocol_names(apps, schema_editor):
    # Get the models
    LibraryProtocol = apps.get_model("library_sample_shared", "LibraryProtocol")
    HistoricalLibraryProtocol = apps.get_model(
        "library_sample_shared", "HistoricalLibraryProtocol"
    )

    print(
        "\nWe'll only allow alphanumeric, dash, underscore, spaces, parentheses, colons, dots, and single quotes as LibraryProtocol names..."
    )
    logger.info(
        "\nWe'll only allow alphanumeric, dash, underscore, spaces, parentheses, colons, dots, and single quotes as LibraryProtocol names..."
    )

    # Clean current data
    changes_count = 0
    for protocol in LibraryProtocol.objects.all():
        old_name = protocol.name
        # Replace any characters that aren't alphanumeric, dash, underscore, space, parentheses, colons, dots, or single quotes with underscore
        new_name = re.sub(r"[^a-zA-Z0-9_\- \(\):\.\']", "_", old_name)
        if old_name != new_name:
            print(f"Updating LibraryProtocol: '{old_name}' -> '{new_name}'")
            logger.info(f"Updating LibraryProtocol: '{old_name}' -> '{new_name}'")
            protocol.name = new_name
            protocol.save(update_fields=["name"])
            changes_count += 1

    if changes_count > 0:
        print(f"Updated {changes_count} LibraryProtocol records")
        logger.info(f"Updated {changes_count} LibraryProtocol records")

    # Clean historical data
    h_changes_count = 0
    for h_protocol in HistoricalLibraryProtocol.objects.all():
        old_name = h_protocol.name
        new_name = re.sub(r"[^a-zA-Z0-9_\- \(\):\.\']", "_", old_name)
        if old_name != new_name:
            h_protocol.name = new_name
            h_protocol.save(update_fields=["name"])
            h_changes_count += 1

    if h_changes_count > 0:
        print(f"Updated {h_changes_count} HistoricalLibraryProtocol records")
        logger.info(f"Updated {h_changes_count} HistoricalLibraryProtocol records")


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "library_sample_shared",
            "0013_alter_indexpair_char_coord_historicalorganism_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(clean_library_protocol_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="historicallibraryprotocol",
            name="name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9_\\- \\(\\):\\.\\']+$",
                        "Only alphanumeric characters, spaces, dashes, underscores, parentheses, colons, dots, and single quotes are allowed.",
                    )
                ],
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="libraryprotocol",
            name="name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9_\\- \\(\\):\\.\\']+$",
                        "Only alphanumeric characters, spaces, dashes, underscores, parentheses, colons, dots, and single quotes are allowed.",
                    )
                ],
                verbose_name="Name",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalIndexPair",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "char_coord",
                    models.CharField(
                        max_length=1,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]$",
                                "Only capital alphabetical characters are allowed.",
                            )
                        ],
                        verbose_name="Character Coordinate",
                    ),
                ),
                (
                    "num_coord",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Numeric Coordinate",
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "index1",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="library_sample_shared.indexi7",
                        verbose_name="Index 1",
                    ),
                ),
                (
                    "index2",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="library_sample_shared.indexi5",
                        verbose_name="Index 2",
                    ),
                ),
                (
                    "index_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="library_sample_shared.indextype",
                        verbose_name="Index Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Index Pair",
                "verbose_name_plural": "historical Index Pairs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
