# Generated by Django 4.2.20 on 2025-08-01 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "library_sample_shared",
            "0014_alter_historicallibraryprotocol_name_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE library_sample_shared_indextype "
                        "DROP COLUMN IF EXISTS index_length"
                    ),
                    reverse_sql=(
                        "ALTER TABLE library_sample_shared_indextype "
                        "ADD COLUMN index_length varchar(2) NOT NULL DEFAULT '8'"
                    ),
                )
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="indextype",
                    name="index_length",
                )
            ],
        ),
    ]
