# Generated by Django 4.2.20 on 2025-08-01 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "library_sample_shared",
            "0014_remove_index_length_field",
        ),
        (
            "library_sample_shared",
            "0014_alter_historicallibraryprotocol_name_and_more",
        ),
    ]

    # No schema changes; this migration merely linearizes history.
    operations = []
