# Generated by Django 5.2.17 on 2026-09-11 11:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("library_sample_shared", "0015_alter_historicallibraryprotocol_name_and_more"),
        # Every prior library/sample migration still refers to this model
        # under its old name (LibraryType); the rename must not land until
        # all of them have applied, otherwise those earlier migrations fail
        # to resolve their lazy FK reference against the renamed model.
        ("library", "0008_update_library_fields"),
        ("sample", "0010_update_sample_measurement_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LibraryType",
            new_name="AnalysisType",
        ),
        migrations.RenameModel(
            old_name="HistoricalLibraryType",
            new_name="HistoricalAnalysisType",
        ),
        migrations.AlterModelOptions(
            name="analysistype",
            options={
                "verbose_name": "Analysis Type",
                "verbose_name_plural": "Analysis Types",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalanalysistype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Analysis Type",
                "verbose_name_plural": "historical Analysis Types",
            },
        ),
    ]
