# Generated by Django 5.2.17 on 2026-09-09 17:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0015_alter_library_library_type"),
        ("library_sample_shared", "0015_alter_historicallibraryprotocol_name_and_more"),
        ("sample", "0019_alter_sample_index_i5_alter_sample_index_i7_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LibraryType",
            new_name="AnalysisType",
        ),
        migrations.RenameModel(
            old_name="HistoricalLibraryType",
            new_name="HistoricalAnalysisType",
        ),
        migrations.AlterModelOptions(
            name="analysistype",
            options={
                "verbose_name": "Analysis Type",
                "verbose_name_plural": "Analysis Types",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalanalysistype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Analysis Type",
                "verbose_name_plural": "historical Analysis Types",
            },
        ),
    ]
