# Generated by Django 5.2.17 on 2026-09-11 11:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("library_sample_shared", "0015_alter_historicallibraryprotocol_name_and_more"),
        # library.0009-0012 and sample.0011-0017 rebuild the
        # complete_library_data_mv / complete_sample_data_mv summary tables
        # using common.sql_legacy_pre_analysis_type_rename, which still
        # reads the library_type_id column/library_sample_shared_librarytype
        # table under their old names. This rename must not land until all
        # of them have applied, or that frozen SQL breaks against columns
        # that no longer exist.
        ("library", "0012_alter_library_name"),
        ("sample", "0017_alter_sample_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LibraryType",
            new_name="AnalysisType",
        ),
        migrations.RenameModel(
            old_name="HistoricalLibraryType",
            new_name="HistoricalAnalysisType",
        ),
        migrations.AlterModelOptions(
            name="analysistype",
            options={
                "verbose_name": "Analysis Type",
                "verbose_name_plural": "Analysis Types",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalanalysistype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Analysis Type",
                "verbose_name_plural": "historical Analysis Types",
            },
        ),
    ]
