# Generated by Django 4.2.19 on 2025-04-29 08:23

import django.core.validators
import re
from django.db import migrations, models
import logging

logger = logging.getLogger(__name__)


def clean_library_protocol_names(apps, schema_editor):
    # Get the models
    LibraryProtocol = apps.get_model("library_sample_shared", "LibraryProtocol")
    HistoricalLibraryProtocol = apps.get_model(
        "library_sample_shared", "HistoricalLibraryProtocol"
    )

    print(
        "\nWe'll only allow alphanumeric, dash, underscore, spaces, parentheses, colons, dots, and single quotes as LibraryProtocol names..."
    )
    logger.info(
        "\nWe'll only allow alphanumeric, dash, underscore, spaces, parentheses, colons, dots, and single quotes as LibraryProtocol names..."
    )

    # Clean current data
    changes_count = 0
    for protocol in LibraryProtocol.objects.all():
        old_name = protocol.name
        # Replace any characters that aren't alphanumeric, dash, underscore, space, parentheses, colons, dots, or single quotes with underscore
        new_name = re.sub(r"[^a-zA-Z0-9_\- \(\):\.\']", "_", old_name)
        if old_name != new_name:
            print(f"Updating LibraryProtocol: '{old_name}' -> '{new_name}'")
            logger.info(f"Updating LibraryProtocol: '{old_name}' -> '{new_name}'")
            protocol.name = new_name
            protocol.save(update_fields=["name"])
            changes_count += 1

    if changes_count > 0:
        print(f"Updated {changes_count} LibraryProtocol records")
        logger.info(f"Updated {changes_count} LibraryProtocol records")

    # Clean historical data
    h_changes_count = 0
    for h_protocol in HistoricalLibraryProtocol.objects.all():
        old_name = h_protocol.name
        new_name = re.sub(r"[^a-zA-Z0-9_\- \(\):\.\']", "_", old_name)
        if old_name != new_name:
            h_protocol.name = new_name
            h_protocol.save(update_fields=["name"])
            h_changes_count += 1

    if h_changes_count > 0:
        print(f"Updated {h_changes_count} HistoricalLibraryProtocol records")
        logger.info(f"Updated {h_changes_count} HistoricalLibraryProtocol records")


class Migration(migrations.Migration):
    dependencies = [
        ("library_sample_shared", "0014_historicalindexpair"),
    ]

    operations = [
        # First clean the data
        migrations.RunPython(clean_library_protocol_names, migrations.RunPython.noop),
        # Then add the validators
        migrations.AlterField(
            model_name="historicallibraryprotocol",
            name="name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        r"^[a-zA-Z0-9_\- \(\):\.\']+$",
                        "Only alphanumeric characters, spaces, dashes, underscores, parentheses, colons, dots, and single quotes are allowed.",
                    )
                ],
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="libraryprotocol",
            name="name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        r"^[a-zA-Z0-9_\- \(\):\.\']+$",
                        "Only alphanumeric characters, spaces, dashes, underscores, parentheses, colons, dots, and single quotes are allowed.",
                    )
                ],
                verbose_name="Name",
            ),
        ),
    ]
