# Generated by Django 3.2.20 on 2023-08-23 10:55

import django.db.models.deletion
import month.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("flowcell", "0001_initial"),
        ("library_sample_shared", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoicingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                ("month", month.models.MonthField(unique=True, verbose_name="Month")),
                (
                    "report",
                    models.FileField(
                        upload_to="invoicing/%Y/%m/", verbose_name="Report"
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoicing Report",
                "verbose_name_plural": "Invoicing Report",
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="LibraryPreparationCosts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
                (
                    "library_protocol",
                    models.OneToOneField(
                        limit_choices_to={"archived": False},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="library_sample_shared.libraryprotocol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Library Preparation Cost",
                "verbose_name_plural": "Library Preparation Costs",
            },
        ),
        migrations.CreateModel(
            name="FixedCosts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
                (
                    "sequencer",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="flowcell.sequencer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fixed Cost",
                "verbose_name_plural": "Fixed Costs",
            },
        ),
        migrations.CreateModel(
            name="SequencingCosts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
                (
                    "read_length",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="library_sample_shared.readlength",
                        verbose_name="Read Length",
                    ),
                ),
                (
                    "sequencer",
                    models.ForeignKey(
                        limit_choices_to={"archived": False},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="flowcell.sequencer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sequencing Cost",
                "verbose_name_plural": "Sequencing Costs",
                "unique_together": {("sequencer", "read_length")},
            },
        ),
    ]
