# Generated by Django 1.11.8 on 2018-11-21 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarypreparationcosts",
            name="library_protocol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="library_sample_shared.LibraryProtocol",
                unique=True,
            ),
        ),
    ]
