# Generated by Django 3.2.16 on 2023-01-24 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_sample_shared", "0008_optional_index1_long"),
        ("invoicing", "0003_dj32_upgrade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarypreparationcosts",
            name="library_protocol",
            field=models.OneToOneField(
                limit_choices_to={"obsolete": 1},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="library_sample_shared.libraryprotocol",
            ),
        ),
    ]
