# Generated by Django 3.2.15 on 2022-12-04 09:41

from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20221031_1657'),
        ('invoicing', '0003_auto_20220818_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryPreparationPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='SequencingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='fixedcosts',
            name='price',
        ),
        migrations.RemoveField(
            model_name='librarypreparationcosts',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sequencingcosts',
            name='price',
        ),
        migrations.AddField(
            model_name='invoicingreport',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='invoicingreport',
            name='month',
            field=month.models.MonthField(verbose_name='Month'),
        ),
        migrations.AddConstraint(
            model_name='invoicingreport',
            constraint=models.UniqueConstraint(fields=('month', 'organization'), name='unique_month_organization'),
        ),
        migrations.AddField(
            model_name='sequencingprice',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='sequencingprice',
            name='sequencing_cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.sequencingcosts'),
        ),
        migrations.AddField(
            model_name='librarypreparationprice',
            name='library_preparation_cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.librarypreparationcosts'),
        ),
        migrations.AddField(
            model_name='librarypreparationprice',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='fixedprice',
            name='fixed_cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.fixedcosts'),
        ),
        migrations.AddField(
            model_name='fixedprice',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.organization', verbose_name='Organization'),
        ),
        migrations.AddConstraint(
            model_name='sequencingprice',
            constraint=models.UniqueConstraint(fields=('sequencing_cost', 'organization'), name='unique_sequencing_cost_organization'),
        ),
        migrations.AddConstraint(
            model_name='librarypreparationprice',
            constraint=models.UniqueConstraint(fields=('library_preparation_cost', 'organization'), name='unique_library_preparation_cost_organization'),
        ),
        migrations.AddConstraint(
            model_name='fixedprice',
            constraint=models.UniqueConstraint(fields=('fixed_cost', 'organization'), name='unique_fixed_cost_organization'),
        ),
    ]
