# Generated by Django 3.2.20 on 2023-08-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowcell', '0004_archived_feature'),
        ('library_sample_shared', '0009_archived_feature'),
        ('invoicing', '0004_alter_librarypreparationcosts_library_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedcosts',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='librarypreparationcosts',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='sequencingcosts',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='librarypreparationcosts',
            name='library_protocol',
            field=models.OneToOneField(limit_choices_to={'archived': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_sample_shared.libraryprotocol'),
        ),
        migrations.AlterField(
            model_name='sequencingcosts',
            name='sequencer',
            field=models.ForeignKey(limit_choices_to={'archived': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowcell.sequencer'),
        ),
    ]
