# Generated by Django 3.2.15 on 2022-10-27 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0004_dj32_upgrade"),
        ("library_preparation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarypreparation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="librarypreparation",
            name="sample",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sample.sample",
                verbose_name="Sample",
            ),
        ),
    ]
