# Generated by Django 3.2.20 on 2023-08-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_preparation", "0002_dj32_upgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarypreparation",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archived"),
        ),
    ]
