# Generated by Django 3.2.14 on 2022-08-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_user_is_bioinformatician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcgroup',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
    ]
