# Generated by Django 3.2.15 on 2022-08-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_principalinvestigator_parent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pi',
        ),
        migrations.AddField(
            model_name='user',
            name='pi',
            field=models.ManyToManyField(blank=True, to='common.PrincipalInvestigator', verbose_name='Principal Investigator'),
        ),
    ]
