# Generated by Django 3.2.15 on 2022-09-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_user_cost_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='costunit',
            name='obsolete',
            field=models.PositiveIntegerField(default=1, verbose_name='Obsolete'),
        ),
    ]
