# Generated by Django 3.2.15 on 2022-09-11 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_costunit_obsolete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalinvestigator',
            name='parent_user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
