# Generated by Django 4.2.7 on 2023-11-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_remove_costunit_obsolete_costunit_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duty',
            name='facility',
        ),
    ]
