# Generated by Django 3.2.20 on 2023-08-23 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0001_initial'),
        ('index_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('lanes', models.PositiveSmallIntegerField(verbose_name='Number of Lanes')),
                ('lane_capacity', models.PositiveSmallIntegerField(verbose_name='Lane Capacity')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
            ],
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, verbose_name='Name')),
                ('loading_concentration', models.FloatField(blank=True, null=True, verbose_name='Loading Concentration')),
                ('phix', models.FloatField(blank=True, null=True, verbose_name='PhiX %')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index_generator.pool', verbose_name='Pool')),
            ],
        ),
        migrations.CreateModel(
            name='Flowcell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('flowcell_id', models.CharField(max_length=50, unique=True, verbose_name='Flowcell ID')),
                ('matrix', models.JSONField(blank=True, null=True, verbose_name='Flowcell Matrix')),
                ('sequences', models.JSONField(blank=True, null=True, verbose_name='Sequences')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('lanes', models.ManyToManyField(blank=True, related_name='flowcell', to='flowcell.Lane')),
                ('requests', models.ManyToManyField(blank=True, related_name='flowcell', to='request.Request')),
                ('sequencer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowcell.sequencer', verbose_name='Sequencer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
