# Generated by Django 3.2.14 on 2022-08-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_generator', '0004_auto_20220818_1435'),
        ('flowcell', '0002_sequencer_obsolete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowcell',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flowcell',
            name='matrix',
            field=models.JSONField(blank=True, null=True, verbose_name='Flowcell Matrix'),
        ),
        migrations.AlterField(
            model_name='flowcell',
            name='sequencer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowcell.sequencer', verbose_name='Sequencer'),
        ),
        migrations.AlterField(
            model_name='flowcell',
            name='sequences',
            field=models.JSONField(blank=True, null=True, verbose_name='Sequences'),
        ),
        migrations.AlterField(
            model_name='lane',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lane',
            name='pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index_generator.pool', verbose_name='Pool'),
        ),
        migrations.AlterField(
            model_name='sequencer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
