# Generated by Django 3.2.20 on 2023-08-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcell', '0003_dj32_upgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencer',
            name='obsolete',
        ),
        migrations.AddField(
            model_name='flowcell',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='sequencer',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
