# Generated by Django 4.2.9 on 2024-04-09 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_preparation", "0003_archived_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarypreparation",
            name="smear_analysis",
            field=models.FloatField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Smear Analysis",
            ),
        ),
    ]
