# Generated by Django 4.2.20 on 2025-05-02 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("library_preparation", "0004_librarypreparation_smear_analysis"),
    ]

    operations = [
        migrations.RenameField(
            model_name="librarypreparation",
            old_name="nM",
            new_name="removed_nM",
        ),
        migrations.RenameField(
            model_name="librarypreparation",
            old_name="qpcr_result",
            new_name="removed_qpcr_result",
        ),
        migrations.RenameField(
            model_name="librarypreparation",
            old_name="spike_in_description",
            new_name="removed_spike_in_description",
        ),
        migrations.RenameField(
            model_name="librarypreparation",
            old_name="spike_in_volume",
            new_name="removed_spike_in_volume",
        ),
    ]
