# Generated by Django 5.2.17 on 2026-09-11 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0005_archived_feature"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InvoicingReport",
        ),
    ]
