"""Frozen snapshot of the complete_library_data_mv / complete_sample_data_mv
SELECT SQL, as it read before the LibraryType -> AnalysisType rename
(library_sample_shared migration 0016).

The historical migrations that (re)built these tables -- library 0009 and
0011, sample 0011 and 0015 -- run before that rename in a fresh migration
replay, so at that point in history library_library/sample_sample still have
a library_type_id column, not analysis_type_id, and
library_sample_shared_librarytype is still the lookup table's name. Those
migrations import this frozen copy instead of common.sql, so future edits to
common.sql (which reflects the CURRENT schema, used at runtime by
common/mviews.py) can't silently break replaying migration history from
scratch. Do not edit this file when common/sql.py changes again -- add a new
legacy snapshot instead, if a future rename breaks replay the same way.
"""

from __future__ import annotations

from typing import Final

from common.sql import (
    LIBRARY_CREATE_TABLE_SQL,
    LIBRARY_DROP_MV_SQL,
    LIBRARY_DROP_VIEW_SQL,
    LIBRARY_INDEX_SQL,
    LIBRARY_INSERT_SQL_TEMPLATE,
    SAMPLE_CREATE_TABLE_SQL,
    SAMPLE_DROP_MV_SQL,
    SAMPLE_INDEX_SQL,
    SAMPLE_INSERT_SQL_TEMPLATE,
)

LIBRARY_SELECT_SQL_TEMPLATE: Final[str] = """
SELECT DISTINCT ON (l.id, r.id)
    l.id AS library_id,
    l.barcode,
    l.name,
    l.comments AS comment_input,
    org.name AS organism_name,
    l.status,
    l.sequencing_depth,
    l.measuring_unit,
    l.measured_value,
    l.measuring_unit_facility,
    l.measured_value_facility,
    l.measured_value_facility AS concentration_library,
    l.percent_total,
    lp.id AS library_protocol_id,
    lp.name AS library_protocol_name,
    lt.id AS analysis_type_id,
    lt.name AS analysis_type_name,
    l.read_length_id,
    rl.name AS read_length_name,
    l.size_distribution_facility AS average_fragment_size,
    it.name AS index_type_name,
    CASE
        WHEN ip.char_coord IS NOT NULL AND ip.num_coord IS NOT NULL
        THEN ip.char_coord || ip.num_coord::text
        ELSE ''
    END AS coordinate,
    l.index_i7,
    COALESCE(i7.prefix, '') || COALESCE(i7.number, '') AS i7_id,
    l.index_i5,
    COALESCE(i5.prefix, '') || COALESCE(i5.number, '') AS i5_id,
    r.id AS request_id,
    r.name AS request_name,
    r.create_time AS create_time,
    pools.pool_names,
    fcids.flowcell_ids,
    fcids.sequencer_ids,
    fcids.sequencer_names,
    to_tsvector('simple',
        COALESCE(l.name,'') || ' ' ||
        COALESCE(l.comments,'') || ' ' ||
        COALESCE(org.name,'') || ' ' ||
        COALESCE(l.barcode,'') || ' ' ||
        COALESCE(r.name,'') || ' ' ||
        COALESCE(array_to_string(pools.pool_names,' '),'') || ' ' ||
        COALESCE(array_to_string(fcids.flowcell_ids,' '),'')
    ) AS search_vector
FROM library_library AS l
JOIN request_request_libraries AS rrl ON l.id = rrl.library_id
JOIN request_request AS r ON rrl.request_id = r.id
LEFT JOIN library_sample_shared_organism AS org ON l.organism_id = org.id
LEFT JOIN library_sample_shared_libraryprotocol AS lp ON l.library_protocol_id = lp.id
LEFT JOIN library_sample_shared_librarytype AS lt ON l.library_type_id = lt.id
LEFT JOIN library_sample_shared_indextype AS it ON l.index_type_id = it.id
LEFT JOIN library_sample_shared_readlength AS rl ON l.read_length_id = rl.id
LEFT JOIN library_sample_shared_indexi7 AS i7
    ON i7.index = l.index_i7
    AND EXISTS (
        SELECT 1
        FROM library_sample_shared_indextype_indices_i7 AS iti7
        WHERE iti7.indexi7_id = i7.id
          AND iti7.indextype_id = l.index_type_id
    )
LEFT JOIN library_sample_shared_indexi5 AS i5
    ON i5.index = l.index_i5
    AND EXISTS (
        SELECT 1
        FROM library_sample_shared_indextype_indices_i5 AS iti5
        WHERE iti5.indexi5_id = i5.id
          AND iti5.indextype_id = l.index_type_id
    )
LEFT JOIN library_sample_shared_indexpair AS ip
    ON ip.index1_id = i7.id AND ip.index2_id = i5.id AND ip.index_type_id = l.index_type_id
LEFT JOIN LATERAL (
    SELECT array_agg(DISTINCT p.name) AS pool_names
    FROM index_generator_pool_libraries pl
    JOIN index_generator_pool p ON pl.pool_id = p.id
    WHERE pl.library_id = l.id
) pools ON TRUE
LEFT JOIN LATERAL (
    SELECT
        array_agg(DISTINCT fc.flowcell_id) AS flowcell_ids,
        array_agg(DISTINCT seq.id::integer) AS sequencer_ids,
        array_agg(DISTINCT seq.name) AS sequencer_names
    FROM index_generator_pool_libraries ipl2
    JOIN index_generator_pool p2 ON ipl2.pool_id = p2.id
    JOIN flowcell_lane lane2 ON lane2.pool_id = p2.id
    JOIN flowcell_flowcell_lanes fc_lane ON fc_lane.lane_id = lane2.id
    JOIN flowcell_flowcell fc ON fc_lane.flowcell_id = fc.id
    LEFT JOIN flowcell_sequencer seq ON fc.sequencer_id = seq.id
    WHERE ipl2.library_id = l.id
) fcids ON TRUE
{where_clause}
ORDER BY l.id, r.id;
""".strip()

SAMPLE_SELECT_SQL_TEMPLATE: Final[str] = """
SELECT DISTINCT ON (s.id, r.id)
    s.id AS sample_id,
    s.barcode,
    s.name,
    s.comments AS comment_input,
    org.name AS organism_name,
    s.status,
    s.sequencing_depth,
    nat.id AS nucleic_acid_type_id,
    nat.name AS nucleic_acid_type_name,
    s.measuring_unit,
    s.measured_value,
    s.measuring_unit_facility,
    s.measured_value_facility,
    lp2.concentration_library,
    s.gmo,
    lp.id AS library_protocol_id,
    lp.name AS library_protocol_name,
    lt.id AS analysis_type_id,
    lt.name AS analysis_type_name,
    s.read_length_id,
    rl.name AS read_length_name,
    lp2.mean_fragment_size AS average_fragment_size,
    lp2.starting_amount,
    lp2.pcr_cycles,
    it.name AS index_type_name,
    CASE
        WHEN ip.char_coord IS NOT NULL AND ip.num_coord IS NOT NULL
        THEN ip.char_coord || ip.num_coord::text
        ELSE ''
    END AS coordinate,
    s.index_i7,
    COALESCE(i7.prefix, '') || COALESCE(i7.number, '') AS i7_id,
    s.index_i5,
    COALESCE(i5.prefix, '') || COALESCE(i5.number, '') AS i5_id,
    r.id AS request_id,
    r.name AS request_name,
    r.create_time AS create_time,
    pools.pool_names,
    fcids.flowcell_ids,
    fcids.sequencer_ids,
    fcids.sequencer_names,
    to_tsvector('simple',
        COALESCE(s.name,'') || ' ' ||
        COALESCE(s.comments,'') || ' ' ||
        COALESCE(org.name,'') || ' ' ||
        COALESCE(s.barcode,'') || ' ' ||
        COALESCE(r.name,'') || ' ' ||
        COALESCE(array_to_string(pools.pool_names,' '),'') || ' ' ||
        COALESCE(array_to_string(fcids.flowcell_ids,' '),'')
    ) AS search_vector
FROM sample_sample AS s
JOIN request_request_samples AS rrs ON s.id = rrs.sample_id
JOIN request_request AS r ON rrs.request_id = r.id
LEFT JOIN library_sample_shared_organism AS org ON s.organism_id = org.id
LEFT JOIN sample_nucleicacidtype AS nat ON s.nucleic_acid_type_id = nat.id
LEFT JOIN library_sample_shared_libraryprotocol AS lp ON s.library_protocol_id = lp.id
LEFT JOIN library_sample_shared_librarytype AS lt ON s.library_type_id = lt.id
LEFT JOIN library_sample_shared_indextype AS it ON s.index_type_id = it.id
LEFT JOIN library_preparation_librarypreparation AS lp2 ON lp2.sample_id = s.id
LEFT JOIN library_sample_shared_readlength AS rl ON s.read_length_id = rl.id
LEFT JOIN library_sample_shared_indexi7 AS i7
    ON i7.index = s.index_i7
    AND EXISTS (
        SELECT 1
        FROM library_sample_shared_indextype_indices_i7 AS iti7
        WHERE iti7.indexi7_id = i7.id
          AND iti7.indextype_id = s.index_type_id
    )
LEFT JOIN library_sample_shared_indexi5 AS i5
    ON i5.index = s.index_i5
    AND EXISTS (
        SELECT 1
        FROM library_sample_shared_indextype_indices_i5 AS iti5
        WHERE iti5.indexi5_id = i5.id
          AND iti5.indextype_id = s.index_type_id
    )
LEFT JOIN library_sample_shared_indexpair AS ip
    ON ip.index1_id = i7.id AND ip.index2_id = i5.id AND ip.index_type_id = s.index_type_id
LEFT JOIN LATERAL (
    SELECT array_agg(DISTINCT p.name) AS pool_names
    FROM index_generator_pool_samples ps
    JOIN index_generator_pool p ON ps.pool_id = p.id
    WHERE ps.sample_id = s.id
) pools ON TRUE
LEFT JOIN LATERAL (
    SELECT
        array_agg(DISTINCT fc.flowcell_id) AS flowcell_ids,
        array_agg(DISTINCT seq.id::integer) AS sequencer_ids,
        array_agg(DISTINCT seq.name) AS sequencer_names
    FROM index_generator_pool_samples ps2
    JOIN index_generator_pool p2 ON ps2.pool_id = p2.id
    JOIN flowcell_lane lane2 ON lane2.pool_id = p2.id
    JOIN flowcell_flowcell_lanes fc_lane ON fc_lane.lane_id = lane2.id
    JOIN flowcell_flowcell fc ON fc_lane.flowcell_id = fc.id
    LEFT JOIN flowcell_sequencer seq ON fc.sequencer_id = seq.id
    WHERE ps2.sample_id = s.id
) fcids ON TRUE
{where_clause}
ORDER BY s.id, r.id;
""".strip()


def library_select_sql(where_clause: str = "") -> str:
    return LIBRARY_SELECT_SQL_TEMPLATE.format(where_clause=where_clause)


def sample_select_sql(where_clause: str = "") -> str:
    return SAMPLE_SELECT_SQL_TEMPLATE.format(where_clause=where_clause)


def library_insert_sql_from_select(select_clause: str) -> str:
    return LIBRARY_INSERT_SQL_TEMPLATE.format(select_clause=select_clause)


def sample_insert_sql_from_select(select_clause: str) -> str:
    return SAMPLE_INSERT_SQL_TEMPLATE.format(select_clause=select_clause)


def library_insert_sql(where_clause: str = "") -> str:
    return library_insert_sql_from_select(library_select_sql(where_clause))


def sample_insert_sql(where_clause: str = "") -> str:
    return sample_insert_sql_from_select(sample_select_sql(where_clause))


def library_create_mv_sql(where_clause: str = "") -> str:
    select_sql = library_select_sql(where_clause).strip()
    return f"""
CREATE MATERIALIZED VIEW complete_library_data_mv AS
{select_sql}
""".strip()


def sample_create_mv_sql(where_clause: str = "") -> str:
    select_sql = sample_select_sql(where_clause).strip()
    return f"""
CREATE MATERIALIZED VIEW complete_sample_data_mv AS
{select_sql}
""".strip()


__all__ = [
    "LIBRARY_CREATE_TABLE_SQL",
    "LIBRARY_DROP_MV_SQL",
    "LIBRARY_DROP_VIEW_SQL",
    "LIBRARY_INDEX_SQL",
    "SAMPLE_CREATE_TABLE_SQL",
    "SAMPLE_DROP_MV_SQL",
    "SAMPLE_INDEX_SQL",
    "library_create_mv_sql",
    "library_insert_sql",
    "sample_create_mv_sql",
    "sample_insert_sql",
]
