# Generated by Django 4.2.7 on 2023-11-01 16:20

from django.db import migrations, models
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_request_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='filepaths',
            field=models.JSONField(default=request.models.filepaths_default),
        ),
        migrations.AddField(
            model_name='request',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Token'),
        ),
    ]
