# Generated by Django 3.2.15 on 2022-08-28 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_principalinvestigator_parent_user'),
        ('request', '0002_auto_20220818_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='pi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.principalinvestigator', verbose_name='PI'),
        ),
    ]
