# Generated by Django 3.2.20 on 2023-08-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_dj32_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
