# Generated by Django 3.2.15 on 2022-09-16 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0003_request_pi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='pi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_pi', to=settings.AUTH_USER_MODEL, verbose_name='PI'),
        ),
    ]
