# Generated by Django 4.2.6 on 2023-10-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0003_archived_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="filepaths",
            field=models.JSONField(default={"data": None, "metadata": None}),
        ),
    ]
