# Generated by Django 4.2.6 on 2023-10-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0004_request_filepaths"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="token",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="Token"
            ),
        ),
    ]
