# Generated by Django 3.2.16 on 2023-07-28 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0007_request_samples_submitted_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_handler', to=settings.AUTH_USER_MODEL, verbose_name='Handler'),
        ),
    ]
