# Generated by Django 4.2.7 on 2023-11-03 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0010_request_filepaths_request_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approval_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Approval Time'),
        ),
        migrations.AddField(
            model_name='request',
            name='approval_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_approval_user', to=settings.AUTH_USER_MODEL, verbose_name='approval user'),
        ),
    ]
