# Generated by Django 3.2.20 on 2023-08-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0004_dj32_upgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="nucleicacidtype",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archived"),
        ),
        migrations.AddField(
            model_name="sample",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archived"),
        ),
    ]
