# Generated by Django 4.2.9 on 2024-02-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0005_archived_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nucleicacidtype",
            name="type",
            field=models.CharField(
                choices=[("DNA", "DNA"), ("RNA", "RNA"), ("Cells", "Cells")],
                default="DNA",
                max_length=5,
                verbose_name="Type",
            ),
        ),
    ]
