# Generated by Django 4.2.16 on 2024-10-23 01:27

import django.core.validators
import django.db.models.deletion
import library_sample_shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "library_sample_shared",
            "0011_alter_indexi5_number_alter_indexi5_prefix_and_more",
        ),
        ("sample", "0006_alter_nucleicacidtype_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nucleicacidtype",
            options={
                "verbose_name": "Input Type",
                "verbose_name_plural": "Input Types",
            },
        ),
        migrations.RenameField(
            model_name="sample",
            old_name="amplification_cycles",
            new_name="removed_amplification_cycles",
        ),
        migrations.RenameField(
            model_name="sample",
            old_name="concentration",
            new_name="measured_value",
        ),
        migrations.RenameField(
            model_name="sample",
            old_name="concentration_method",
            new_name="removed_concentration_method",
        ),
        migrations.RenameField(
            model_name="sample",
            old_name="equal_representation_nucleotides",
            new_name="removed_equal_representation_nucleotides",
        ),
        migrations.RenameField(
            model_name="sample",
            old_name="concentration_facility",
            new_name="measured_value_facility",
        ),
        migrations.RenameField(
            model_name="sample",
            old_name="concentration_method_facility",
            new_name="removed_concentration_method_facility",
        ),
        migrations.AddField(
            model_name="sample",
            name="biosafety_level",
            field=models.CharField(
                choices=[("bsl1", "BSL1"), ("bsl2", "BSL2")],
                max_length=50,
                null=True,
                verbose_name="Biosafety Level",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="gmo",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Genetically Modified Organism"
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="measuring_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ng/µl", "ng/µl (Concentration)"),
                    ("M", "M (Cells)"),
                    ("-", "Unknown"),
                ],
                max_length=50,
                null=True,
                verbose_name="Measuring Unit",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="measuring_unit_facility",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ng/µl", "ng/µl (Concentration)"),
                    ("M", "M (Cells)"),
                    ("-", "Unknown"),
                ],
                max_length=50,
                null=True,
                verbose_name="Measuring Unit (facility)",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="volume",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(10)],
                verbose_name="Volume",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="nucleic_acid_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sample.nucleicacidtype",
                verbose_name="Input Type",
            ),
        ),
    ]
