# Generated by Django 4.2.9 on 2024-07-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0006_alter_nucleicacidtype_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="is_pool_destroyed",
            field=models.BooleanField(default=False, verbose_name="Pool Destroyed"),
        ),
    ]
