# Generated by Django 3.2.16 on 2023-09-29 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_sample_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='nucleicacidtype',
            name='single_cell',
            field=models.BooleanField(default=False, verbose_name='single cell?'),
        ),
        migrations.AddField(
            model_name='sample',
            name='cell_density',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='For single cell projects', null=True, verbose_name='cell density'),
        ),
        migrations.AddField(
            model_name='sample',
            name='cell_viability',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='For single cell projects', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(101)], verbose_name='cell viability'),
        ),
        migrations.AddField(
            model_name='sample',
            name='number_targeted_cells',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='For single cell projects', null=True, verbose_name='number of targeted cells'),
        ),
        migrations.AddField(
            model_name='sample',
            name='starting_number_cells',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='For single cell projects', null=True, verbose_name='starting number of cell'),
        ),
    ]
