# Generated by Django 4.2.16 on 2024-11-04 16:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "library_sample_shared",
            "0013_alter_indexpair_char_coord_historicalorganism_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sample", "0006_alter_nucleicacidtype_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSample",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Create Time"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Update Time"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("status", models.SmallIntegerField(default=0)),
                ("concentration", models.FloatField(verbose_name="Concentration")),
                (
                    "equal_representation_nucleotides",
                    models.BooleanField(
                        default=True, verbose_name="Equal Representation of Nucleotides"
                    ),
                ),
                (
                    "sequencing_depth",
                    models.FloatField(verbose_name="Sequencing Depth"),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Comments"),
                ),
                (
                    "is_pooled",
                    models.BooleanField(default=False, verbose_name="Pooled"),
                ),
                ("barcode", models.CharField(max_length=9, verbose_name="Barcode")),
                (
                    "index_reads",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Index Reads"
                    ),
                ),
                (
                    "index_i7",
                    models.CharField(
                        blank=True, max_length=24, null=True, verbose_name="Index I7"
                    ),
                ),
                (
                    "index_i5",
                    models.CharField(
                        blank=True, max_length=24, null=True, verbose_name="Index I5"
                    ),
                ),
                (
                    "amplification_cycles",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Amplification cycles"
                    ),
                ),
                (
                    "dilution_factor",
                    models.PositiveIntegerField(
                        blank=True, default=1, verbose_name="Dilution Factor"
                    ),
                ),
                (
                    "concentration_facility",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Concentration"
                    ),
                ),
                (
                    "sample_volume_facility",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Sample Volume"
                    ),
                ),
                (
                    "amount_facility",
                    models.FloatField(blank=True, null=True, verbose_name="Amount"),
                ),
                (
                    "size_distribution_facility",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Size Distribution",
                    ),
                ),
                (
                    "comments_facility",
                    models.TextField(blank=True, null=True, verbose_name="Comments"),
                ),
                (
                    "rna_quality",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(11.0),
                        ],
                        verbose_name="RNA Quality",
                    ),
                ),
                (
                    "is_converted",
                    models.BooleanField(default=False, verbose_name="Converted"),
                ),
                (
                    "rna_quality_facility",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(11.0),
                        ],
                        verbose_name="RNA Quality (facility)",
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "concentration_method",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="library_sample_shared.concentrationmethod",
                        verbose_name="Concentration Method",
                    ),
                ),
                (
                    "concentration_method_facility",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="library_sample_shared.concentrationmethod",
                        verbose_name="Concentration Method",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "index_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="library_sample_shared.indextype",
                        verbose_name="Index Type",
                    ),
                ),
                (
                    "library_protocol",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="library_sample_shared.libraryprotocol",
                        verbose_name="Library Protocol",
                    ),
                ),
                (
                    "library_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="library_sample_shared.librarytype",
                        verbose_name="Library Type",
                    ),
                ),
                (
                    "nucleic_acid_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sample.nucleicacidtype",
                        verbose_name="Nucleic Acid Type",
                    ),
                ),
                (
                    "organism",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="library_sample_shared.organism",
                        verbose_name="Organism",
                    ),
                ),
                (
                    "read_length",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="library_sample_shared.readlength",
                        verbose_name="Read Length",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Sample",
                "verbose_name_plural": "historical Samples",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
