# Generated by Django 4.2.14 on 2024-08-06 15:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0006_alter_nucleicacidtype_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nucleicacidtype",
            options={
                "verbose_name": "Input Type",
                "verbose_name_plural": "Input Types",
            },
        ),
        migrations.AddField(
            model_name="sample",
            name="biosafety_level",
            field=models.CharField(
                choices=[("bsl1", "BSL1"), ("bsl2", "BSL2")],
                max_length=50,
                null=True,
                verbose_name="Biosafety Level",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="gmo",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Genetically Modified Organism"
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="measuring_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bp", "bp (DNA)"),
                    ("nt", "nt (RNA)"),
                    ("RQN", "RNQ (RNA (total))"),
                    ("M", "M (Cells)"),
                    ("-", "Measure for Me"),
                ],
                max_length=50,
                null=True,
                verbose_name="Measuring Unit",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="volume",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(10)],
                verbose_name="Volume",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="nucleic_acid_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sample.nucleicacidtype",
                verbose_name="Input Type",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="rna_quality",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(-1)],
                verbose_name="Measured Value",
            ),
        ),
    ]
