# Generated by Django 4.2.16 on 2024-11-29 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0007_historicalsample"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalSample",
        ),
    ]
