# Generated by Django 4.2.15 on 2024-08-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sample",
            "0007_alter_nucleicacidtype_options_sample_biosafety_level_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="sample",
            old_name="rna_quality",
            new_name="measured_value",
        ),
    ]
