# Generated by Django 4.2.16 on 2024-10-23 01:38

import django.core.validators
import library_sample_shared.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "library_sample_shared",
            "0011_alter_indexi5_number_alter_indexi5_prefix_and_more",
        ),
        ("sample", "0007_alter_nucleicacidtype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="measured_value",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(-1)],
                verbose_name="Measured Value",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="measured_value_facility",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(-1)],
                verbose_name="Measured Value (facility)",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="removed_concentration_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(
                    library_sample_shared.models.get_removed_concentrationmethod
                ),
                to="library_sample_shared.concentrationmethod",
                verbose_name="Concentration Method",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="removed_equal_representation_nucleotides",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name="Equal Representation of Nucleotides",
            ),
        ),
    ]
