# Generated by Django 4.2.16 on 2024-11-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_alter_sample_measured_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='measuring_unit',
            field=models.CharField(blank=True, choices=[('concentration', 'ng/µl (Concentration)'), ('m', 'M (Cells)'), ('-', 'Unknown')], max_length=50, null=True, verbose_name='Measuring Unit'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='measuring_unit_facility',
            field=models.CharField(blank=True, choices=[('concentration', 'ng/µl (Concentration)'), ('m', 'M (Cells)'), ('-', 'Unknown')], max_length=50, null=True, verbose_name='Measuring Unit (facility)'),
        ),
    ]
