# Generated by Django 4.2.7 on 2023-12-14 10:51

from django.db import migrations, models
import library_sample_shared.models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0014_remove_indextype_obsolete_and_more'),
        ('sample', '0009_nucleicacidtype_archived_sample_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='concentration_method',
            field=models.ForeignKey(null=True, on_delete=models.SET(library_sample_shared.models.get_removed_concentrationmethod), to='library_sample_shared.concentrationmethod', verbose_name='Concentration Method'),
        ),
    ]
