# Generated by Django 4.2.20 on 2025-05-15 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0009_alter_nucleicacidtype_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="percent_total",
        ),
    ]
