# Generated by Django 4.2.16 on 2025-01-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_alter_sample_size_distribution_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='gmo_facility',
            field=models.BooleanField(blank=True, null=True, verbose_name='Genetically Modified Organism (facility)'),
        ),
    ]
