# Generated by Django 5.2.17 on 2026-09-11 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0010_update_sample_measurement_fields"),
        ("library_sample_shared", "0016_rename_librarytype_analysistype_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sample",
            old_name="library_type",
            new_name="analysis_type",
        ),
        migrations.AlterField(
            model_name="sample",
            name="analysis_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="library_sample_shared.analysistype",
                verbose_name="Analysis Type",
            ),
        ),
    ]
