# Generated by Django 4.2.20 on 2025-06-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_remove_sample_percent_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='measuring_unit',
            field=models.CharField(blank=True, choices=[('concentration', 'ng/µl (Concentration)'), ('m', 'M (Cells)'), ('k', 'k (Cells)'), ('-', 'Unknown')], max_length=50, null=True, verbose_name='Measuring Unit'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='measuring_unit_facility',
            field=models.CharField(blank=True, choices=[('concentration', 'ng/µl (Concentration)'), ('m', 'M (Cells)'), ('k', 'k (Cells)'), ('-', 'Unknown')], max_length=50, null=True, verbose_name='Measuring Unit (facility)'),
        ),
    ]
