# Generated by Django 4.2.20 on 2025-09-11 02:12

import django.contrib.postgres.fields
from django.db import migrations, models


DROP_MV_SQL = "DROP MATERIALIZED VIEW IF EXISTS complete_sample_data_mv CASCADE;"

CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS complete_sample_data_mv (
    sample_id INTEGER PRIMARY KEY,
    barcode VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    status INTEGER NOT NULL,
    sequencing_depth DOUBLE PRECISION,
    nucleic_acid_type_id INTEGER,
    nucleic_acid_type_name VARCHAR(100),
    measuring_unit VARCHAR(50),
    measured_value DOUBLE PRECISION,
    concentration_library DOUBLE PRECISION,
    gmo BOOLEAN,
    library_protocol_id INTEGER,
    library_protocol_name VARCHAR(150),
    analysis_type_id INTEGER,
    analysis_type_name VARCHAR(200),
    read_length_id INTEGER,
    read_length_name VARCHAR(50),
    average_fragment_size DOUBLE PRECISION,
    starting_amount DOUBLE PRECISION,
    pcr_cycles INTEGER,
    index_type_name VARCHAR(100),
    coordinate VARCHAR(3),
    index_i7 VARCHAR(24),
    i7_id VARCHAR(50),
    index_i5 VARCHAR(24),
    i5_id VARCHAR(50),
    request_id INTEGER,
    request_name VARCHAR(255),
    create_time TIMESTAMP WITH TIME ZONE,
    pool_names VARCHAR(100)[],
    flowcell_ids VARCHAR(50)[],
    sequencer_ids INTEGER[],
    sequencer_names VARCHAR(50)[],
    search_vector TSVECTOR
);
"""

SAMPLE_SELECT_SQL = """
SELECT DISTINCT ON (s.id, r.id)
    s.id AS sample_id,
    s.barcode,
    s.name,
    s.status,
    s.sequencing_depth,
    nat.id AS nucleic_acid_type_id,
    nat.name AS nucleic_acid_type_name,
    s.measuring_unit,
    s.measured_value,
    lp2.concentration_library,
    s.gmo,
    lp.id AS library_protocol_id,
    lp.name AS library_protocol_name,
    lt.id AS analysis_type_id,
    lt.name AS analysis_type_name,
    s.read_length_id,
    rl.name AS read_length_name,
    lp2.mean_fragment_size AS average_fragment_size,
    lp2.starting_amount,
    lp2.pcr_cycles,
    it.name AS index_type_name,
    CASE
        WHEN ip.char_coord IS NOT NULL AND ip.num_coord IS NOT NULL
        THEN ip.char_coord || ip.num_coord::text
        ELSE ''
    END AS coordinate,
    s.index_i7,
    COALESCE(i7.prefix, '') || COALESCE(i7.number, '') AS i7_id,
    s.index_i5,
    COALESCE(i5.prefix, '') || COALESCE(i5.number, '') AS i5_id,
    r.id AS request_id,
    r.name AS request_name,
    r.create_time AS create_time,
    pools.pool_names,
    fcids.flowcell_ids,
    fcids.sequencer_ids,
    fcids.sequencer_names,
    to_tsvector('simple',
        COALESCE(s.name,'') || ' ' ||
        COALESCE(s.barcode,'') || ' ' ||
        COALESCE(r.name,'') || ' ' ||
        COALESCE(array_to_string(pools.pool_names,' '),'') || ' ' ||
        COALESCE(array_to_string(fcids.flowcell_ids,' '),'')
    ) AS search_vector
FROM sample_sample AS s
JOIN request_request_samples AS rrs ON s.id = rrs.sample_id
JOIN request_request AS r ON rrs.request_id = r.id
LEFT JOIN sample_nucleicacidtype AS nat ON s.nucleic_acid_type_id = nat.id
LEFT JOIN library_sample_shared_libraryprotocol AS lp ON s.library_protocol_id = lp.id
LEFT JOIN library_sample_shared_librarytype AS lt ON s.library_type_id = lt.id
LEFT JOIN library_sample_shared_indextype AS it ON s.index_type_id = it.id
LEFT JOIN library_preparation_librarypreparation AS lp2 ON lp2.sample_id = s.id
LEFT JOIN library_sample_shared_readlength AS rl ON s.read_length_id = rl.id
LEFT JOIN library_sample_shared_indexi7 AS i7 ON i7.index = s.index_i7
LEFT JOIN library_sample_shared_indexi5 AS i5 ON i5.index = s.index_i5
LEFT JOIN library_sample_shared_indexpair AS ip
    ON ip.index1_id = i7.id AND ip.index2_id = i5.id
LEFT JOIN LATERAL (
    SELECT array_agg(DISTINCT p.name) AS pool_names
    FROM index_generator_pool_samples ps
    JOIN index_generator_pool p ON ps.pool_id = p.id
    WHERE ps.sample_id = s.id
) pools ON TRUE
LEFT JOIN LATERAL (
    SELECT
        array_agg(DISTINCT fc.flowcell_id) AS flowcell_ids,
        array_agg(DISTINCT seq.id::integer) AS sequencer_ids,
        array_agg(DISTINCT seq.name) AS sequencer_names
    FROM index_generator_pool_samples ps2
    JOIN index_generator_pool p2 ON ps2.pool_id = p2.id
    JOIN flowcell_lane lane2 ON lane2.pool_id = p2.id
    JOIN flowcell_flowcell_lanes fc_lane ON fc_lane.lane_id = lane2.id
    JOIN flowcell_flowcell fc ON fc_lane.flowcell_id = fc.id
    LEFT JOIN flowcell_sequencer seq ON fc.sequencer_id = seq.id
    WHERE ps2.sample_id = s.id
) fcids ON TRUE
ORDER BY s.id, r.id;
"""

POPULATE_SQL = f"""
INSERT INTO complete_sample_data_mv (
    sample_id,
    barcode,
    name,
    status,
    sequencing_depth,
    nucleic_acid_type_id,
    nucleic_acid_type_name,
    measuring_unit,
    measured_value,
    concentration_library,
    gmo,
    library_protocol_id,
    library_protocol_name,
    analysis_type_id,
    analysis_type_name,
    read_length_id,
    read_length_name,
    average_fragment_size,
    starting_amount,
    pcr_cycles,
    index_type_name,
    coordinate,
    index_i7,
    i7_id,
    index_i5,
    i5_id,
    request_id,
    request_name,
    create_time,
    pool_names,
    flowcell_ids,
    sequencer_ids,
    sequencer_names,
    search_vector
)
{SAMPLE_SELECT_SQL}
"""

INDEX_SQL = """
CREATE UNIQUE INDEX IF NOT EXISTS idx_csd_mv_pk ON complete_sample_data_mv (sample_id, request_id);
CREATE INDEX IF NOT EXISTS idx_csd_mv_create_time ON complete_sample_data_mv (create_time DESC);
CREATE INDEX IF NOT EXISTS idx_csd_mv_request_id ON complete_sample_data_mv (request_id);
CREATE INDEX IF NOT EXISTS idx_csd_mv_request_name ON complete_sample_data_mv (request_name);
CREATE INDEX IF NOT EXISTS idx_csd_mv_status ON complete_sample_data_mv (status);
CREATE INDEX IF NOT EXISTS idx_csd_mv_library_protocol_id ON complete_sample_data_mv (library_protocol_id);
CREATE INDEX IF NOT EXISTS idx_csd_mv_analysis_type_id ON complete_sample_data_mv (analysis_type_id);
CREATE INDEX IF NOT EXISTS idx_csd_mv_read_length_id ON complete_sample_data_mv (read_length_id);
CREATE INDEX IF NOT EXISTS idx_csd_mv_sequencer_ids ON complete_sample_data_mv USING GIN (sequencer_ids);
CREATE INDEX IF NOT EXISTS idx_csd_mv_flowcell_ids ON complete_sample_data_mv USING GIN (flowcell_ids);
CREATE INDEX IF NOT EXISTS idx_csd_mv_pool_names ON complete_sample_data_mv USING GIN (pool_names);
CREATE INDEX IF NOT EXISTS idx_csd_mv_search_vector ON complete_sample_data_mv USING GIN (search_vector);
"""

CREATE_MV_SQL = """
CREATE MATERIALIZED VIEW complete_sample_data_mv AS
{SAMPLE_SELECT_SQL}
""".format(SAMPLE_SELECT_SQL=SAMPLE_SELECT_SQL.strip())


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_update_sample_measurement_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=DROP_MV_SQL,
                    reverse_sql="DROP TABLE IF EXISTS complete_sample_data_mv CASCADE;",
                ),
                migrations.RunSQL(
                    sql=CREATE_TABLE_SQL,
                    reverse_sql=CREATE_MV_SQL,
                ),
                migrations.RunSQL(
                    sql="TRUNCATE TABLE complete_sample_data_mv;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=POPULATE_SQL,
                    reverse_sql="REFRESH MATERIALIZED VIEW complete_sample_data_mv;",
                ),
                migrations.RunSQL(
                    sql=INDEX_SQL,
                    reverse_sql=INDEX_SQL,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='CompleteSampleData',
                    fields=[
                        ('sample_id', models.IntegerField(primary_key=True, serialize=False)),
                        ('barcode', models.CharField(max_length=100)),
                        ('name', models.CharField(max_length=255)),
                        ('status', models.IntegerField()),
                        ('sequencing_depth', models.FloatField()),
                        ('nucleic_acid_type_id', models.IntegerField()),
                        ('nucleic_acid_type_name', models.CharField(max_length=100)),
                        ('measuring_unit', models.CharField(max_length=50)),
                        ('measured_value', models.FloatField()),
                        ('concentration_library', models.FloatField()),
                        ('gmo', models.BooleanField()),
                        ('library_protocol_id', models.IntegerField()),
                        ('library_protocol_name', models.CharField(max_length=150, null=True)),
                        ('analysis_type_id', models.IntegerField()),
                        ('analysis_type_name', models.CharField(max_length=200, null=True)),
                        ('read_length_id', models.IntegerField(null=True)),
                        ('read_length_name', models.CharField(max_length=50, null=True)),
                        ('average_fragment_size', models.FloatField()),
                        ('starting_amount', models.FloatField()),
                        ('pcr_cycles', models.IntegerField()),
                        ('index_type_name', models.CharField(max_length=100, null=True)),
                        ('coordinate', models.CharField(max_length=3, null=True)),
                        ('index_i7', models.CharField(max_length=24, null=True)),
                        ('i7_id', models.CharField(max_length=50, null=True)),
                        ('index_i5', models.CharField(max_length=24, null=True)),
                        ('i5_id', models.CharField(max_length=50, null=True)),
                        ('request_id', models.IntegerField()),
                        ('request_name', models.CharField(max_length=255)),
                        ('create_time', models.DateTimeField()),
                        ('pool_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                        ('flowcell_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                        ('sequencer_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                        ('sequencer_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                    ],
                    options={
                        'db_table': 'complete_sample_data_mv',
                        'managed': False,
                    },
                ),
            ],
        ),
    ]
