# Generated by Django 4.2.20 on 2025-09-11 02:12

import django.contrib.postgres.fields
from django.db import migrations, models

from common.sql import (
    SAMPLE_CREATE_TABLE_SQL,
    SAMPLE_DROP_MV_SQL,
    SAMPLE_INDEX_SQL,
    sample_create_mv_sql,
    sample_insert_sql,
)

DROP_MV_SQL = SAMPLE_DROP_MV_SQL

CREATE_TABLE_SQL = SAMPLE_CREATE_TABLE_SQL

POPULATE_SQL = sample_insert_sql()

INDEX_SQL = SAMPLE_INDEX_SQL

CREATE_MV_SQL = sample_create_mv_sql()


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0010_update_sample_measurement_fields"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=DROP_MV_SQL,
                    reverse_sql="DROP TABLE IF EXISTS complete_sample_data_mv CASCADE;",
                ),
                migrations.RunSQL(
                    sql=CREATE_TABLE_SQL,
                    reverse_sql=CREATE_MV_SQL,
                ),
                migrations.RunSQL(
                    sql="TRUNCATE TABLE complete_sample_data_mv;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=POPULATE_SQL,
                    reverse_sql="REFRESH MATERIALIZED VIEW complete_sample_data_mv;",
                ),
                migrations.RunSQL(
                    sql=INDEX_SQL,
                    reverse_sql=INDEX_SQL,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="CompleteSampleData",
                    fields=[
                        (
                            "sample_id",
                            models.IntegerField(primary_key=True, serialize=False),
                        ),
                        ("barcode", models.CharField(max_length=100)),
                        ("name", models.CharField(max_length=255)),
                        ("status", models.IntegerField()),
                        ("sequencing_depth", models.FloatField()),
                        ("nucleic_acid_type_id", models.IntegerField()),
                        ("nucleic_acid_type_name", models.CharField(max_length=100)),
                        ("measuring_unit", models.CharField(max_length=50)),
                        ("measured_value", models.FloatField()),
                        ("concentration_library", models.FloatField()),
                        ("gmo", models.BooleanField()),
                        ("library_protocol_id", models.IntegerField()),
                        (
                            "library_protocol_name",
                            models.CharField(max_length=150, null=True),
                        ),
                        ("analysis_type_id", models.IntegerField()),
                        (
                            "analysis_type_name",
                            models.CharField(max_length=200, null=True),
                        ),
                        ("read_length_id", models.IntegerField(null=True)),
                        (
                            "read_length_name",
                            models.CharField(max_length=50, null=True),
                        ),
                        ("average_fragment_size", models.FloatField()),
                        ("starting_amount", models.FloatField()),
                        ("pcr_cycles", models.IntegerField()),
                        (
                            "index_type_name",
                            models.CharField(max_length=100, null=True),
                        ),
                        ("coordinate", models.CharField(max_length=3, null=True)),
                        ("index_i7", models.CharField(max_length=24, null=True)),
                        ("i7_id", models.CharField(max_length=50, null=True)),
                        ("index_i5", models.CharField(max_length=24, null=True)),
                        ("i5_id", models.CharField(max_length=50, null=True)),
                        ("request_id", models.IntegerField()),
                        ("request_name", models.CharField(max_length=255)),
                        ("create_time", models.DateTimeField()),
                        (
                            "pool_names",
                            django.contrib.postgres.fields.ArrayField(
                                base_field=models.CharField(max_length=100),
                                null=True,
                                size=None,
                            ),
                        ),
                        (
                            "flowcell_ids",
                            django.contrib.postgres.fields.ArrayField(
                                base_field=models.CharField(max_length=50),
                                null=True,
                                size=None,
                            ),
                        ),
                        (
                            "sequencer_ids",
                            django.contrib.postgres.fields.ArrayField(
                                base_field=models.IntegerField(), null=True, size=None
                            ),
                        ),
                        (
                            "sequencer_names",
                            django.contrib.postgres.fields.ArrayField(
                                base_field=models.CharField(max_length=50),
                                null=True,
                                size=None,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "complete_sample_data_mv",
                        "managed": False,
                    },
                ),
            ],
        ),
    ]
