# Generated by Django 5.2.7 on 2025-11-26 18:44

import library_sample_shared.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_sample_shared", "0015_alter_historicallibraryprotocol_name_and_more"),
        ("sample", "0011_refresh_complete_sample_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="removed_concentration_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(
                    library_sample_shared.models.get_removed_concentrationmethod
                ),
                to="library_sample_shared.concentrationmethod",
                verbose_name="Concentration Method",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="removed_equal_representation_nucleotides",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name="Equal Representation of Nucleotides",
            ),
        ),
    ]
