# Generated by Django 4.2.20 on 2025-11-12 04:30

from django.db import migrations, models

from common.sql import (
    SAMPLE_CREATE_TABLE_SQL,
    SAMPLE_DROP_MV_SQL,
    SAMPLE_INDEX_SQL,
    sample_create_mv_sql,
    sample_insert_sql,
)

DROP_MV_SQL = SAMPLE_DROP_MV_SQL
CREATE_TABLE_SQL = SAMPLE_CREATE_TABLE_SQL
POPULATE_SQL = sample_insert_sql()
INDEX_SQL = SAMPLE_INDEX_SQL
CREATE_MV_SQL = sample_create_mv_sql()


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0011_refresh_complete_sample_data"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=DROP_MV_SQL,
                    reverse_sql=CREATE_MV_SQL,
                ),
                migrations.RunSQL(
                    sql=CREATE_TABLE_SQL,
                    reverse_sql=DROP_MV_SQL,
                ),
                migrations.RunSQL(
                    sql="TRUNCATE TABLE complete_sample_data_mv;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=POPULATE_SQL,
                    reverse_sql="REFRESH MATERIALIZED VIEW complete_sample_data_mv;",
                ),
                migrations.RunSQL(
                    sql=INDEX_SQL,
                    reverse_sql=INDEX_SQL,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="completesampledata",
                    name="measured_value_facility",
                    field=models.FloatField(),
                ),
                migrations.AddField(
                    model_name="completesampledata",
                    name="measuring_unit_facility",
                    field=models.CharField(max_length=50),
                ),
            ],
        ),
    ]
