# Generated by Django 4.2.15 on 2024-09-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0011_alter_sample_measured_value_facility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="removed_equal_representation_nucleotides",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name="Equal Representation of Nucleotides",
            ),
        ),
    ]
