# Generated by Django 4.2.19 on 2025-02-18 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0008_delete_historicalsample"),
        ("sample", "0011_sample_gmo_facility"),
    ]

    operations = []
