# Generated by Django 4.2.20 on 2025-07-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0012_completesampleview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteSampleData',
            fields=[
                ('sample_id', models.IntegerField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('measuring_unit', models.CharField(max_length=50)),
                ('request_id', models.IntegerField()),
                ('request_name', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'complete_sample_data',
                'managed': False,
            },
        ),
    ]
