# Generated by Django 4.2.20 on 2025-08-12 17:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0012_completesampleview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteSampleData',
            fields=[
                ('sample_id', models.IntegerField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('sequencing_depth', models.FloatField()),
                ('nucleic_acid_type_id', models.IntegerField()),
                ('nucleic_acid_type_name', models.CharField(max_length=100)),
                ('measuring_unit', models.CharField(max_length=50)),
                ('measured_value', models.FloatField()),
                ('concentration_library', models.FloatField()),
                ('gmo', models.BooleanField()),
                ('library_protocol_id', models.IntegerField()),
                ('library_protocol_name', models.CharField(max_length=150, null=True)),
                ('analysis_type_id', models.IntegerField()),
                ('analysis_type_name', models.CharField(max_length=200, null=True)),
                ('read_length_id', models.IntegerField(null=True)),
                ('read_length_name', models.CharField(max_length=50, null=True)),
                ('average_fragment_size', models.FloatField()),
                ('starting_amount', models.FloatField()),
                ('pcr_cycles', models.IntegerField()),
                ('index_type_name', models.CharField(max_length=100, null=True)),
                ('coordinate', models.CharField(max_length=3, null=True)),
                ('index_i7', models.CharField(max_length=24, null=True)),
                ('i7_id', models.CharField(max_length=50, null=True)),
                ('index_i5', models.CharField(max_length=24, null=True)),
                ('i5_id', models.CharField(max_length=50, null=True)),
                ('request_id', models.IntegerField()),
                ('request_name', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
                ('pool_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('flowcell_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('sequencer_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('sequencer_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
            ],
            options={
                'db_table': 'complete_sample_data',
                'managed': False,
            },
        ),
    ]
