# Generated by Django 4.2.19 on 2025-02-26 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0012_merge_20250218_1348"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sample",
            old_name="dilution_factor",
            new_name="removed_dilution_factor",
        ),
    ]
