# Generated by Django 4.2.20 on 2025-07-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0012_completesampleview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteSampleData',
            fields=[
                ('sample_id', models.IntegerField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('sequencing_depth', models.FloatField()),
                ('nucleic_acid_type_id', models.IntegerField()),
                ('nucleic_acid_type_name', models.CharField(max_length=100)),
                ('measuring_unit', models.CharField(max_length=50)),
                ('measured_value', models.FloatField()),
                ('gmo', models.BooleanField()),
                ('library_protocol_id', models.IntegerField()),
                ('library_protocol_name', models.CharField(max_length=150, null=True)),
                ('analysis_type_id', models.IntegerField()),
                ('analysis_type_name', models.CharField(max_length=200, null=True)),
                ('average_fragment_size', models.FloatField()),
                ('index_type_name', models.CharField(max_length=100, null=True)),
                ('index_reads', models.PositiveSmallIntegerField(null=True)),
                ('index_i7', models.CharField(max_length=24, null=True)),
                ('index_i5', models.CharField(max_length=24, null=True)),
                ('request_id', models.IntegerField()),
                ('request_name', models.CharField(max_length=255)),
                ('pool_name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'complete_sample_data',
                'managed': False,
            },
        ),
    ]
