# Generated by Django 4.2.15 on 2024-09-25 00:31

from django.db import migrations, models
import library_sample_shared.models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0011_alter_indexi5_number_alter_indexi5_prefix_and_more'),
        ('sample', '0012_alter_sample_removed_equal_representation_nucleotides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='removed_concentration_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(library_sample_shared.models.get_removed_concentrationmethod), to='library_sample_shared.concentrationmethod', verbose_name='Concentration Method'),
        ),
    ]
