# Generated by Codex on 2026-01-20
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0013_alter_sample_measuring_unit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sample",
            old_name="rna_quality",
            new_name="removed_rna_quality",
        ),
    ]
