# Generated by Codex on 2026-04-09

from django.db import migrations, models

from common.sql import sample_insert_sql


POPULATE_SQL = sample_insert_sql()


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0014_rename_rna_quality"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
ALTER TABLE complete_sample_data_mv
ADD COLUMN IF NOT EXISTS comment_input TEXT;
ALTER TABLE complete_sample_data_mv
ADD COLUMN IF NOT EXISTS organism_name VARCHAR(100);
TRUNCATE TABLE complete_sample_data_mv;
""",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=POPULATE_SQL,
                    reverse_sql="TRUNCATE TABLE complete_sample_data_mv;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="completesampledata",
                    name="comment_input",
                    field=models.TextField(null=True),
                ),
                migrations.AddField(
                    model_name="completesampledata",
                    name="organism_name",
                    field=models.CharField(max_length=100, null=True),
                ),
            ],
        ),
    ]
