# Generated by Django 4.2.20 on 2025-09-11 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0015_completesampledatamv_delete_completesampledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_volume_facility',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sample Volume'),
        ),
    ]
