# Generated by Django 5.2.15 on 2026-07-06 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0016_reorder_sample_measuring_unit_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="name",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        "^.*[A-Za-z0-9]$", "Name must end with a letter or number."
                    )
                ],
                verbose_name="Name",
            ),
        ),
    ]
