# Generated by Django 4.2.20 on 2025-10-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0016_alter_sample_sample_volume_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='measuring_unit',
            field=models.CharField(blank=True, choices=[('ng/µl', 'ng/µl (Concentration)'), ('M', 'M (Cells)'), ('k', 'k (Cells)'), ('x', 'Unknown')], max_length=50, null=True, verbose_name='Measuring Unit'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='measuring_unit_facility',
            field=models.CharField(blank=True, choices=[('ng/µl', 'ng/µl (Concentration)'), ('M', 'M (Cells)'), ('k', 'k (Cells)'), ('x', 'Unknown')], max_length=50, null=True, verbose_name='Measuring Unit (facility)'),
        ),
    ]
