# Generated by Django 5.2.17 on 2026-09-03 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0017_alter_sample_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="name",
            field=models.CharField(
                max_length=99,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9_-]+$",
                        "Only letters, numbers, underscores and hyphens are allowed.",
                    ),
                    django.core.validators.RegexValidator(
                        "^.*[A-Za-z0-9]$", "Name must end with a letter or number."
                    ),
                ],
                verbose_name="Name",
            ),
        ),
    ]
