# Generated by Django 5.2.17 on 2026-09-03 16:39

import re

import django.core.validators
from django.db import migrations, models
from django.db.models import Q

NAME_CHARSET_RE = re.compile(r"[^A-Za-z0-9_-]")
NAME_MAX_LENGTH = 99


def sanitize_name(name):
    sanitized = NAME_CHARSET_RE.sub("_", name)
    sanitized = re.sub(r"_{2,}", "_", sanitized)
    sanitized = sanitized[:NAME_MAX_LENGTH]
    sanitized = re.sub(r"[^A-Za-z0-9]+$", "", sanitized)
    return sanitized or "unnamed"


def fix_invalid_names(apps, schema_editor):
    Sample = apps.get_model("sample", "Sample")
    invalid = Sample.objects.filter(
        ~Q(name__regex=r"^[A-Za-z0-9_-]{1,%d}$" % NAME_MAX_LENGTH)
        | Q(name__regex=r"[^A-Za-z0-9]$")
    )
    for sample in invalid.iterator():
        sample.name = sanitize_name(sample.name)
        sample.save(update_fields=["name"])


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0017_alter_sample_name"),
    ]

    operations = [
        migrations.RunPython(fix_invalid_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="sample",
            name="name",
            field=models.CharField(
                max_length=99,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9_-]+$",
                        "Only letters, numbers, underscores and hyphens are allowed.",
                    ),
                    django.core.validators.RegexValidator(
                        "^.*[A-Za-z0-9]$", "Name must end with a letter or number."
                    ),
                ],
                verbose_name="Name",
            ),
        ),
    ]
