# Generated by Django 5.2.7 on 2025-11-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0017_replace_complete_sample_data_mv_with_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='measuring_unit',
            field=models.CharField(blank=True, choices=[('ng/µl', 'ng/µl (Concentration)'), ('M', 'M (Cells)'), ('k', 'k (Cells)'), ('Unknown', 'Unknown')], max_length=50, null=True, verbose_name='Measuring Unit'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='measuring_unit_facility',
            field=models.CharField(blank=True, choices=[('ng/µl', 'ng/µl (Concentration)'), ('M', 'M (Cells)'), ('k', 'k (Cells)'), ('Unknown', 'Unknown')], max_length=50, null=True, verbose_name='Measuring Unit (facility)'),
        ),
    ]
