# Generated by Django 5.2.17 on 2026-09-03 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0018_alter_sample_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="index_i5",
            field=models.CharField(
                blank=True,
                max_length=24,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[ATCG]+$", "Only A, T, C, and G (uppercase) are allowed."
                    )
                ],
                verbose_name="Index I5",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="index_i7",
            field=models.CharField(
                blank=True,
                max_length=24,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[ATCG]+$", "Only A, T, C, and G (uppercase) are allowed."
                    )
                ],
                verbose_name="Index I7",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="size_distribution_facility",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Size Distribution",
            ),
        ),
    ]
