# Generated by Django 5.2.17 on 2026-09-09 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_sample_shared", "0016_rename_librarytype_analysistype_and_more"),
        ("sample", "0021_rename_library_type_sample_analysis_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="analysis_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="library_sample_shared.analysistype",
                verbose_name="Analysis Type",
            ),
        ),
    ]
