# Generated by Django 3.2.16 on 2023-07-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0009_alter_readlength_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodecounter',
            name='last_id',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
    ]
