# Generated by Django 3.2.16 on 2023-07-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0010_alter_barcodecounter_last_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodecounter',
            name='last_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='barcodecounter',
            name='year',
            field=models.PositiveSmallIntegerField(default=2018),
        ),
        migrations.AddConstraint(
            model_name='barcodecounter',
            constraint=models.UniqueConstraint(fields=('year', 'last_id'), name='unique_year_last_id'),
        ),
    ]
