# Generated by Django 4.2.6 on 2023-10-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0013_auto_20231013_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indextype',
            name='obsolete',
        ),
        migrations.RemoveField(
            model_name='libraryprotocol',
            name='obsolete',
        ),
        migrations.RemoveField(
            model_name='readlength',
            name='obsolete',
        ),
        migrations.AddField(
            model_name='indexi5',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='indexi7',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='indexpair',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='indextype',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='libraryprotocol',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='librarytype',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='organism',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='readlength',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
