# Generated by Django 3.2.16 on 2023-06-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0008_optional_index1_long'),
        ('index_generator', '0006_auto_20230326_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poolsize',
            options={'ordering': ['sequencer', 'size', 'cycles']},
        ),
        migrations.RemoveConstraint(
            model_name='poolsize',
            name='unique_pool_size',
        ),
        migrations.AddField(
            model_name='poolsize',
            name='cycles',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of cycles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poolsize',
            name='read_lengths',
            field=models.ManyToManyField(related_name='pool_size', to='library_sample_shared.ReadLength', verbose_name='read lengths'),
        ),
        migrations.AddConstraint(
            model_name='poolsize',
            constraint=models.UniqueConstraint(fields=('sequencer', 'size', 'cycles', 'lanes', 'obsolete'), name='unique_pool_size'),
        ),
    ]
