# Generated by Django 4.2.7 on 2024-01-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_generator', '0009_alter_pool_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolsize',
            name='short_name',
            field=models.CharField(default='PX', max_length=20, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
