# Generated by Django 4.2.7 on 2024-02-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_generator', '0010_poolsize_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolsize',
            name='short_name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
    ]
