# Generated by Django 3.2.20 on 2023-08-23 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sample", "0001_initial"),
        ("library", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pooling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "concentration_c1",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Concentration C1"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                (
                    "library",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="library.library",
                        verbose_name="Library",
                    ),
                ),
                (
                    "sample",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sample.sample",
                        verbose_name="Sample",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pooling",
                "verbose_name_plural": "Pooling",
            },
        ),
    ]
