# Generated by Django 3.2.15 on 2022-10-27 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0003_dj32_upgrade"),
        ("sample", "0004_dj32_upgrade"),
        ("pooling", "0002_pooling_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pooling",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pooling",
            name="library",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="library.library",
                verbose_name="Library",
            ),
        ),
        migrations.AlterField(
            model_name="pooling",
            name="sample",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sample.sample",
                verbose_name="Sample",
            ),
        ),
    ]
