# Generated by Django 3.2.16 on 2023-03-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_dj32_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sample_volume_user',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sample Volume'),
        ),
    ]
