# Generated by Django 3.2.20 on 2023-09-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_archived_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="duty",
            name="comment",
            field=models.TextField(
                blank=True, max_length=2500, null=True, verbose_name="Comment"
            ),
        ),
    ]
