# Generated by Django 3.2.15 on 2022-09-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20220828_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cost_unit',
        ),
    ]
