# Generated by Django 4.2.6 on 2023-10-17 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0008_duty_archived"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="duty",
            name="facility",
        ),
    ]
