# Generated by Django 4.2.19 on 2025-03-13 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_historicalprincipalinvestigator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryPreparationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='File Name')),
                ('file', models.FileField(upload_to='templates/library_preparation/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Library Preparation Template',
                'verbose_name_plural': 'Templates ➜ Library Preparation',
            },
        ),
        migrations.CreateModel(
            name='HistoricalLibraryPreparationTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='File Name')),
                ('file', models.TextField(max_length=100)),
                ('uploaded_at', models.DateTimeField(blank=True, editable=False, verbose_name='Uploaded At')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Library Preparation Template',
                'verbose_name_plural': 'historical Templates ➜ Library Preparation',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
