# Generated by Django 5.2.13 on 2026-04-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0017_loadflowcellstemplate_historicalloadflowcellstemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalloadflowcellstemplate",
            name="file",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalloadflowcellstemplate",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
    ]
