# Generated by Django 5.2.15 on 2026-07-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0019_runstats_sequencestats_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrunstatisticstemplate",
            name="file",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalrunstatisticstemplate",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsequencesstatisticstemplate",
            name="file",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalsequencesstatisticstemplate",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
    ]
