# Generated by Django 5.2.17 on 2026-09-11 11:35

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0021_merge_common_0020_migrations"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachmentFileType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Use letters and numbers separated by single underscores.",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9]+(?:_[A-Za-z0-9]+)*$",
                                "Use letters and numbers separated by single underscores; spaces are not allowed.",
                            )
                        ],
                        verbose_name="Name",
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
            ],
            options={
                "verbose_name": "Attachment File Type",
                "verbose_name_plural": "Attachment File Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InvoicingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="File Name")),
                ("file", models.FileField(upload_to="templates/invoicing/")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
            ],
            options={
                "verbose_name": "Invoicing Template",
                "verbose_name_plural": "Templates -> Invoicing",
            },
        ),
        migrations.AddField(
            model_name="historicalprincipalinvestigator",
            name="deliver_to",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IT filesystem directory token to deliver to when it differs from the PI name (e.g. 'cisse' for PI 'Cissé'). Leave empty to use the PI name.",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z]+$",
                        "Only lowercase a-z characters are allowed, or leave empty.",
                    )
                ],
                verbose_name="Delivery directory",
            ),
        ),
        migrations.AddField(
            model_name="principalinvestigator",
            name="deliver_to",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IT filesystem directory token to deliver to when it differs from the PI name (e.g. 'cisse' for PI 'Cissé'). Leave empty to use the PI name.",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z]+$",
                        "Only lowercase a-z characters are allowed, or leave empty.",
                    )
                ],
                verbose_name="Delivery directory",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalAttachmentFileType",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Use letters and numbers separated by single underscores.",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9]+(?:_[A-Za-z0-9]+)*$",
                                "Use letters and numbers separated by single underscores; spaces are not allowed.",
                            )
                        ],
                        verbose_name="Name",
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Attachment File Type",
                "verbose_name_plural": "historical Attachment File Types",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInvoicingTemplate",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="File Name")),
                ("file", models.TextField(max_length=100)),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Uploaded At"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Invoicing Template",
                "verbose_name_plural": "historical Templates -> Invoicing",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
