# Generated by Django 5.2.16 on 2026-07-29 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0021_merge_common_0020_migrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprincipalinvestigator",
            name="deliver_to",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IT filesystem directory token to deliver to when it differs from the PI name (e.g. 'cisse' for PI 'Cissé'). Leave empty to use the PI name.",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z]+$",
                        "Only lowercase a-z characters are allowed, or leave empty.",
                    )
                ],
                verbose_name="Delivery directory",
            ),
        ),
        migrations.AddField(
            model_name="principalinvestigator",
            name="deliver_to",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IT filesystem directory token to deliver to when it differs from the PI name (e.g. 'cisse' for PI 'Cissé'). Leave empty to use the PI name.",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z]+$",
                        "Only lowercase a-z characters are allowed, or leave empty.",
                    )
                ],
                verbose_name="Delivery directory",
            ),
        ),
    ]
