# Generated by Django 5.2.16 on 2026-08-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_historicalprincipalinvestigator_deliver_to_and_more'),
        ('common', '0022_invoicingtemplate'),
    ]

    operations = [
    ]
