# Generated by Django 3.2.16 on 2023-03-19 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_generator', '0005_auto_20230308_1753'),
        ('invoicing', '0005_auto_20221204_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingcosts',
            name='pool_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index_generator.poolsize', verbose_name='Sequencing kit'),
        ),
        migrations.AlterUniqueTogether(
            name='sequencingcosts',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sequencingcosts',
            name='read_length',
        ),
        migrations.RemoveField(
            model_name='sequencingcosts',
            name='sequencer',
        ),
    ]
