# Generated by Django 4.2.6 on 2023-10-16 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0014_remove_indextype_obsolete_and_more'),
        ('invoicing', '0006_auto_20230319_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedcosts',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='fixedprice',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='invoicingreport',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='librarypreparationcosts',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='librarypreparationprice',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='sequencingcosts',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='sequencingprice',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='librarypreparationcosts',
            name='library_protocol',
            field=models.OneToOneField(limit_choices_to={'archived': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_sample_shared.libraryprotocol'),
        ),
    ]
