# Generated by Django 3.2.16 on 2022-10-28 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_sample_shared", "0007_dj32_upgrade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexpair",
            name="index1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="library_sample_shared.indexi7",
                verbose_name="Index 1",
            ),
        ),
    ]
