# Generated by Django 3.2.16 on 2023-04-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_sample_shared", "0008_optional_index1_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcodecounter",
            name="last_id",
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
    ]
