# Generated by Django 3.2.16 on 2023-06-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0008_optional_index1_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readlength',
            name='name',
            field=models.CharField(help_text='AxB, where A and B are integers', max_length=50, verbose_name='Name'),
        ),
    ]
