# Generated by Django 3.2.15 on 2022-10-31 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0010_auto_20220818_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpair',
            name='index1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_sample_shared.indexi7', verbose_name='Index 1'),
        ),
    ]
