# Generated by Django 3.2.20 on 2023-08-21 15:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import library_sample_shared.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library_sample_shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NucleicAcidType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA')], default='DNA', max_length=3, verbose_name='Type')),
                ('status', models.PositiveIntegerField(default=1, verbose_name='Status')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
            ],
            options={
                'verbose_name': 'Nucleic Acid Type',
                'verbose_name_plural': 'Nucleic Acid Types',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('status', models.SmallIntegerField(default=0)),
                ('concentration', models.FloatField(verbose_name='Concentration')),
                ('equal_representation_nucleotides', models.BooleanField(default=True, verbose_name='Equal Representation of Nucleotides')),
                ('sequencing_depth', models.FloatField(verbose_name='Sequencing Depth')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('is_pooled', models.BooleanField(default=False, verbose_name='Pooled')),
                ('barcode', models.CharField(max_length=9, verbose_name='Barcode')),
                ('index_reads', models.PositiveSmallIntegerField(default=0, verbose_name='Index Reads')),
                ('index_i7', models.CharField(blank=True, max_length=24, null=True, verbose_name='Index I7')),
                ('index_i5', models.CharField(blank=True, max_length=24, null=True, verbose_name='Index I5')),
                ('amplification_cycles', models.PositiveIntegerField(blank=True, null=True, verbose_name='Amplification cycles')),
                ('dilution_factor', models.PositiveIntegerField(blank=True, default=1, verbose_name='Dilution Factor')),
                ('concentration_facility', models.FloatField(blank=True, null=True, verbose_name='Concentration')),
                ('sample_volume_facility', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sample Volume')),
                ('amount_facility', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('size_distribution_facility', models.CharField(blank=True, max_length=200, null=True, verbose_name='Size Distribution')),
                ('comments_facility', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('rna_quality', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(11.0)], verbose_name='RNA Quality')),
                ('is_converted', models.BooleanField(default=False, verbose_name='Converted')),
                ('rna_quality_facility', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(11.0)], verbose_name='RNA Quality (facility)')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('concentration_method', models.ForeignKey(on_delete=models.SET(library_sample_shared.models.get_removed_concentrationmethod), to='library_sample_shared.concentrationmethod', verbose_name='Concentration Method')),
                ('concentration_method_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='library_sample_shared.concentrationmethod', verbose_name='Concentration Method')),
                ('index_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_sample_shared.indextype', verbose_name='Index Type')),
                ('library_protocol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_sample_shared.libraryprotocol', verbose_name='Library Protocol')),
                ('library_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_sample_shared.librarytype', verbose_name='Library Type')),
                ('nucleic_acid_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.nucleicacidtype', verbose_name='Nucleic Acid Type')),
                ('organism', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_sample_shared.organism', verbose_name='Organism')),
                ('read_length', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_sample_shared.readlength', verbose_name='Read Length')),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Samples',
            },
        ),
    ]
