# Generated by Django 3.2.14 on 2022-08-18 12:35

from django.db import migrations, models
import django.db.models.deletion
import library_sample_shared.models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0010_auto_20220818_1435'),
        ('sample', '0003_auto_20200227_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucleicacidtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='concentration_method',
            field=models.ForeignKey(on_delete=models.SET(library_sample_shared.models.get_removed_concentrationmethod), to='library_sample_shared.concentrationmethod', verbose_name='Concentration Method'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='concentration_method_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='library_sample_shared.concentrationmethod', verbose_name='Concentration Method'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='index_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_sample_shared.indextype', verbose_name='Index Type'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='library_protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_sample_shared.libraryprotocol', verbose_name='Library Protocol'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='library_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_sample_shared.librarytype', verbose_name='Library Type'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='nucleic_acid_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.nucleicacidtype', verbose_name='Nucleic Acid Type'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='organism',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_sample_shared.organism', verbose_name='Organism'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='read_length',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_sample_shared.readlength', verbose_name='Read Length'),
        ),
    ]
