# Generated by Django 4.2.6 on 2023-10-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_alter_nucleicacidtype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nucleicacidtype',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='sample',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
