# Generated by Django 3.2.16 on 2023-03-08 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowcell', '0004_auto_20230308_1753'),
        ('index_generator', '0004_dj32_upgrade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poolsize',
            options={'ordering': ['sequencer', 'size']},
        ),
        migrations.RemoveField(
            model_name='poolsize',
            name='multiplier',
        ),
        migrations.AddField(
            model_name='poolsize',
            name='sequencer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowcell.sequencer', verbose_name='Sequencer'),
        ),
    ]
