# Generated by Django 4.2.6 on 2023-10-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_generator', '0007_auto_20230611_1200'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='poolsize',
            name='unique_pool_size',
        ),
        migrations.RemoveField(
            model_name='poolsize',
            name='obsolete',
        ),
        migrations.AddField(
            model_name='pool',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='poolsize',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddConstraint(
            model_name='poolsize',
            constraint=models.UniqueConstraint(fields=('sequencer', 'size', 'cycles', 'lanes', 'archived'), name='unique_pool_size'),
        ),
    ]
