# Generated by Django 4.2.7 on 2023-11-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_generator', '0008_remove_poolsize_unique_pool_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
