# Generated by Django 3.2.16 on 2023-03-08 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_generator', '0004_dj32_upgrade'),
        ('flowcell', '0003_dj32_upgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowcell',
            name='sequencer',
        ),
        migrations.RemoveField(
            model_name='sequencer',
            name='lane_capacity',
        ),
        migrations.AddField(
            model_name='flowcell',
            name='pool_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index_generator.poolsize', verbose_name='Pool Size'),
        ),
    ]
