# Generated by Django 5.2.16 on 2026-07-30 08:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flowcell", "0004_archived_feature"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalFlowcell",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Create Time"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Update Time"
                    ),
                ),
                (
                    "flowcell_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Flowcell ID"
                    ),
                ),
                (
                    "matrix",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Flowcell Matrix"
                    ),
                ),
                (
                    "sequences",
                    models.JSONField(blank=True, null=True, verbose_name="Sequences"),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sequencer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="flowcell.sequencer",
                        verbose_name="Sequencer",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical flowcell",
                "verbose_name_plural": "historical flowcells",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
