# Generated by Django 4.2.9 on 2024-04-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcell', '0007_remove_sequencer_obsolete_flowcell_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowcell',
            name='index1_cycles',
        ),
        migrations.RemoveField(
            model_name='flowcell',
            name='index2_cycles',
        ),
        migrations.RemoveField(
            model_name='flowcell',
            name='library_prep_kits',
        ),
        migrations.RemoveField(
            model_name='flowcell',
            name='read1_cycles',
        ),
        migrations.RemoveField(
            model_name='flowcell',
            name='read2_cycles',
        ),
        migrations.RemoveField(
            model_name='flowcell',
            name='run_name',
        ),
        migrations.AddField(
            model_name='flowcell',
            name='sample_sheet',
            field=models.JSONField(blank=True, null=True, verbose_name='sample sheet'),
        ),
    ]
