# Generated by Django 3.2.16 on 2023-02-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_request_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='pooled_libraries',
            field=models.BooleanField(default=False, verbose_name='Pooled libraries?'),
        ),
        migrations.AddField(
            model_name='request',
            name='pooled_libraries_concentration_user',
            field=models.FloatField(blank=True, null=True, verbose_name='Library pool Concentration by User'),
        ),
        migrations.AddField(
            model_name='request',
            name='pooled_libraries_fragment_size_user',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Library pool Mean Fragment Size by User'),
        ),
        migrations.AddField(
            model_name='request',
            name='pooled_libraries_volume_user',
            field=models.FloatField(blank=True, null=True, verbose_name='Library pool Volume by User'),
        ),
    ]
