# Generated by Django 3.2.16 on 2023-03-08 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_generator', '0005_auto_20230308_1753'),
        ('request', '0005_request_bioinformatician'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='pool_size_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_pool_size_user', to='index_generator.poolsize', verbose_name='Sequencing kit (user)'),
        ),
    ]
