# Generated by Django 3.2.16 on 2023-03-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_request_pool_size_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='samples_submitted_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Samples Submitted Time'),
        ),
    ]
