# Generated by Django 4.2.6 on 2023-10-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_request_handler'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
