# Generated by Django 4.2.7 on 2023-11-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_request_approval_time_request_approval_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='invoice_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Invoice Date'),
        ),
    ]
