# Generated by Django 4.2.7 on 2023-12-11 17:50

from django.db import migrations, models
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0012_request_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approval',
            field=models.JSONField(default=request.models.approval_default),
        ),
        migrations.AddField(
            model_name='request',
            name='metapaths',
            field=models.JSONField(default=request.models.metapaths_default),
        ),
    ]
