# Generated by Django 5.2.14 on 2026-06-30 14:43

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0012_request_related_requests"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalRequest_related_requests",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "from_request",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="request.request",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="request.historicalrequest",
                    ),
                ),
                (
                    "to_request",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="request.request",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalRequest_related_requests",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
