# Generated by Django 4.2.9 on 2024-03-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_request_approval_request_metapaths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerequest',
            name='file',
            field=models.FileField(max_length=200, upload_to='request_files/%Y/%m/%d/'),
        ),
    ]
