# Generated by Django 4.2.9 on 2024-03-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0014_alter_filerequest_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='approval_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Approval Time'),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='invoice_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='request',
            name='samples_submitted_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Samples Submitted Time'),
        ),
    ]
