name: Frontend

on:
  workflow_run:
    workflows:
      - Update
    types:
      - completed
  workflow_dispatch:
  push:
    branches: [develop, update/dependencies]
  pull_request:
    branches: [develop, update/dependencies]
    types: [opened, synchronize, reopened, ready_for_review]


jobs:
  test-and-report:
    if: github.repository == 'maxplanck-ie/parkour2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Playwright rule
        run: |
          make playwright
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: test-suite-report
          # if-no-files-found: ignore  ## default: warn
          path: |
            backend/frontend_testing_suite/videos/
            backend/frontend_testing_suite/results/
          retention-days: 30
